import os
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Header, Query, UploadFile, File, BackgroundTasks, Form, Body
from beanie import PydanticObjectId
from datetime import datetime

from app.schemas.admin_schema import (
    SubjectAnalyticsResponse, AnalyticsTriggerResponse, 
    AdminLectureOperationsResponse, AdminUploadResponse, AdminUploadVideoRequest
)
from app.schemas.ai_schema import PresentationResponse
from app.models.subject_analytics import SubjectAnalytics
from app.models.lecture import Lecture, LectureSource
from app.models.subject import Subject
from app.models.user import User

from app.ai.analytics import generate_subject_analytics
from app.ai.presentation import generate_presentation
from app.knowledge.upload_pdf import process_pdf_background
from app.knowledge.video_processor import process_video_background
from app.auth.dependencies import get_current_admin_user

router = APIRouter(prefix="/admin", tags=["Admin"])

@router.post("/analytics/generate", response_model=AnalyticsTriggerResponse, dependencies=[Depends(get_current_admin_user)])
async def trigger_analytics_generation():
    """
    Manually triggers batch LLM analysis of all unanalyzed chat logs 
    across all subjects. Useful for live demos.
    """
    try:
        result = await generate_subject_analytics()
        return AnalyticsTriggerResponse(**result)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate analytics: {str(e)}")

@router.get("/analytics", response_model=List[SubjectAnalyticsResponse], dependencies=[Depends(get_current_admin_user)])
async def get_all_analytics():
    """
    Returns the most recent analytics dashboard data for all subjects.
    """
    analytics = await SubjectAnalytics.find_all().to_list()
    
    response = []
    for a in analytics:
        weak_topics = [{"topic": wt.topic, "frequency_score": wt.frequency_score} for wt in a.weak_topics]
        
        response.append(SubjectAnalyticsResponse(
            subject_id=a.subject_id,
            subject_name=a.subject_name,
            weak_topics=weak_topics,
            common_questions=a.common_questions,
            confusing_concepts=a.confusing_concepts,
            engagement_count=a.engagement_count,
            ai_insight=a.ai_insight,
            last_analyzed_at=a.last_analyzed_at
        ))
        
    return response

@router.get("/presentation/{lecture_id}", response_model=PresentationResponse, dependencies=[Depends(get_current_admin_user)])
async def create_presentation(
    lecture_id: str,
    force_regenerate: bool = Query(False, description="Set to true to ignore the cache and generate a new deck")
):
    """
    Auto-generates a slide deck presentation using RAG from all sources uploaded to the lecture.
    Only accessible by administrators.
    """
    try:
        presentation_doc = await generate_presentation(lecture_id, force_regenerate)
        
        return PresentationResponse(
            lecture_id=lecture_id,
            presentation_title=presentation_doc.presentation_title,
            slides=[s.model_dump() for s in presentation_doc.slides]
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate presentation: {str(e)}")

async def get_or_create_admin_subject() -> Subject:
    """Creates a unified System Admin account and Subject to anchor orphaned admin objects."""
    admin_email = os.getenv("FIRST_SUPERUSER_EMAIL", "admin@lecturebrain.com")
    admin_user = await User.find_one(User.email == admin_email)
    if not admin_user:
        raise HTTPException(status_code=500, detail="Default admin account missing. Run initial setup.")
    
    admin_subject = await Subject.find_one(Subject.name == "System Architecture Presentations")
    if not admin_subject:
        admin_subject = Subject(name="System Architecture Presentations", owner=admin_user)
        await admin_subject.insert()
    
    return admin_subject

@router.post("/upload_pdf", response_model=AdminUploadResponse, dependencies=[Depends(get_current_admin_user)])
async def admin_upload_pdf(
    background_tasks: BackgroundTasks,
    lecture_id: Optional[str] = Form(None),
    file: UploadFile = File(...)
):
    """
    Seamless admin upload. Auto-creates a new Lecture mapped to a System User if no lecture_id is provided.
    """
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported here")

    if not lecture_id:
        admin_subject = await get_or_create_admin_subject()
        lecture = Lecture(
            title=f"Autogenerated Admin Lecture - {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            subject=admin_subject,
            sources=[],
            status="pending"
        )
        await lecture.insert()
        final_lecture_id = str(lecture.id)
    else:
        lecture = await Lecture.get(PydanticObjectId(lecture_id))
        if not lecture:
            raise HTTPException(status_code=404, detail="Lecture not found")
        final_lecture_id = str(lecture.id)

    pdf_bytes = await file.read()

    lecture.sources.append(LectureSource(type="pdf", url="", status="processing"))
    lecture.status = "processing"
    await lecture.save()

    background_tasks.add_task(process_pdf_background, final_lecture_id, pdf_bytes)

    return AdminUploadResponse(
        lecture_id=final_lecture_id,
        status="processing",
        message="PDF upload successful, processing natively in background."
    )

@router.post("/upload_video", response_model=AdminUploadResponse, dependencies=[Depends(get_current_admin_user)])
async def admin_upload_video(
    request: AdminUploadVideoRequest,
    background_tasks: BackgroundTasks
):
    """
    Seamless admin upload. Auto-creates a new Lecture if request.lecture_id is omitted.
    """
    if not request.lecture_id:
        admin_subject = await get_or_create_admin_subject()
        lecture = Lecture(
            title=f"Autogenerated Admin Lecture - {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            subject=admin_subject,
            sources=[],
            status="pending"
        )
        await lecture.insert()
        final_lecture_id = str(lecture.id)
    else:
        lecture = await Lecture.get(PydanticObjectId(request.lecture_id))
        if not lecture:
            raise HTTPException(status_code=404, detail="Lecture not found")
        final_lecture_id = str(lecture.id)

    lecture.sources.append(LectureSource(type="video", url=request.url, status="processing"))
    lecture.status = "processing"
    await lecture.save()

    background_tasks.add_task(process_video_background, final_lecture_id, request.url, request.extract_frames)

    warning = None
    if request.extract_frames:
        warning = "Frame extraction is enabled. Processing will take significantly longer."

    return AdminUploadResponse(
        lecture_id=final_lecture_id,
        status="processing",
        message="Video ingest successful, processing natively in background.",
        warning=warning
    )

@router.get("/operations", response_model=List[AdminLectureOperationsResponse], dependencies=[Depends(get_current_admin_user)])
async def get_admin_operations():
    """
    Returns the processing status of all uploaded lectures for dashboard observability.
    Intended to be polled periodically by the frontend.
    """
    # Fetch all lectures, sorted by newest first
    lectures = await Lecture.find_all().sort("-created_at").to_list()
    
    response = []
    for l in lectures:
        response.append(AdminLectureOperationsResponse(
            lecture_id=str(l.id),
            title=l.title,
            status=l.status,
            job_tracker=l.job_tracker,
            created_at=l.created_at
        ))
        
    return response
